# Generated by Django 3.2.23 on 2024-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240115_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
